/*
 * Copyright © 2002 Sun Microsystems, Inc., 4150 Network Circle, Santa Clara,
 * California 95054, U.S.A. All rights reserved.  Sun Microsystems, Inc. has
 * intellectual property rights relating to technology embodied in the product
 * that is described in this document. In particular, and without limitation,
 * these intellectual property rights may include one or more of the U.S.
 * patents listed at http://www.sun.com/patents and one or more additional
 * patents or pending patent applications in the U.S. and in other countries.
 * U.S. Government Rights - Commercial software. Government users are subject
 * to the Sun Microsystems, Inc. standard license agreement and applicable
 * provisions of the FAR and its supplements.  Use is subject to license terms.
 * Sun,  Sun Microsystems,  the Sun logo and  Java are trademarks or registered
 * trademarks of Sun Microsystems, Inc. in the U.S. and other countries.  This
 * product is covered and controlled by U.S. Export Control laws and may be
 * subject to the export or import laws in other countries.  Nuclear, missile,
 * chemical biological weapons or nuclear maritime end uses or end users,
 * whether direct or indirect, are strictly prohibited.  Export or reexport
 * to countries subject to U.S. embargo or to entities identified on U.S.
 * export exclusion lists, including, but not limited to, the denied persons
 * and specially designated nationals lists is strictly prohibited.
 */

PARSER_BEGIN(IdList)

package test.javacc;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class IdList {

  public static void main(String args[]) throws ParseException, FileNotFoundException {
    IdList parser = new IdList(new FileInputStream("C:/Programme/eclipse-SDK-3.2-win32/eclipse/workspace/Protune/bin/test/javacc/Input.txt"));
    parser.Input();
  }

}

PARSER_END(IdList)

SKIP :
{
  " "
| "\t"
| "\n"
| "\r"
}

TOKEN :
{
	< Digit: ["0"-"9"] >
	< NotZeroDigit: ["1"-"9"] >
}

void Input() :
{
	Token t;
	int i;
}
{
	t = <NonZeroDigit> {i = parseDigit(t.image);}
	( t = <Digit> {i = i*10 + parseDigit(t.image);} )*
	<EOF> {System.out.println(i);}
}

int parseDigit(String s){
	if(s.equals("0")) return 0;
	if(s.equals("1")) return 1;
	if(s.equals("2")) return 2;
	if(s.equals("3")) return 3;
	if(s.equals("4")) return 4;
	if(s.equals("5")) return 5;
	if(s.equals("6")) return 6;
	if(s.equals("7")) return 7;
	if(s.equals("8")) return 8;
	if(s.equals("9")) return 9;
}