/* Generated By:JavaCC: Do not edit this line. PrologGrammarConstants.java */
public interface PrologGrammarConstants {

  int EOF = 0;
  int DIGITS = 18;
  int SMALLLETTERS = 19;
  int BIGLETTERS = 20;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"rule\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\".\"",
    "\"signed\"",
    "\"signature\"",
    "\"policy\"",
    "\"[\"",
    "\"]\"",
    "\"@\"",
    "\"$\"",
    "\"_\"",
    "<DIGITS>",
    "<SMALLLETTERS>",
    "<BIGLETTERS>",
  };

}
