/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.peertrust.parser.protune;

public interface ParserConstants {

  int EOF = 0;
  int COMMENT = 5;
  int OPERATOR = 6;
  int NEGATION = 7;
  int SEPARATOR = 8;
  int IN = 9;
  int DECLCRED = 10;
  int VARIABLE = 11;
  int IDENTIFIER = 12;
  int STRING = 13;
  int STRING_QUOTED = 14;
  int NUMBER = 15;
  int LOWERCASE = 16;
  int UPPERCASE = 17;
  int DIGIT = 18;
  int UNDERSCORE = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMMENT>",
    "<OPERATOR>",
    "<NEGATION>",
    "<SEPARATOR>",
    "\"in\"",
    "<DECLCRED>",
    "<VARIABLE>",
    "<IDENTIFIER>",
    "<STRING>",
    "<STRING_QUOTED>",
    "<NUMBER>",
    "<LOWERCASE>",
    "<UPPERCASE>",
    "<DIGIT>",
    "\"_\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":\"",
  };

}
