/* Generated By:JavaCC: Do not edit this line. ProtunePrologParserConstants.java */
package org.peertrust.parser.protune;

public interface ProtunePrologParserConstants {

  int EOF = 0;
  int COMMENT = 5;
  int RULE = 6;
  int METARULE = 7;
  int ID = 8;
  int PRED = 9;
  int COMPLEX_TERM = 10;
  int NEGATION = 11;
  int IN = 12;
  int DECLARATION = 13;
  int CREDENTIAL = 14;
  int OPERATOR = 15;
  int VARIABLE = 16;
  int IDENTIFIER = 17;
  int STRING = 18;
  int STRING_QUOTED = 19;
  int NUMBER = 20;
  int LOWERCASE = 21;
  int UPPERCASE = 22;
  int DIGIT = 23;
  int UNDERSCORE = 24;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMMENT>",
    "\"rule\"",
    "\"metarule\"",
    "\"id\"",
    "\"pred\"",
    "\"complex_term\"",
    "\"not\"",
    "\"in\"",
    "\"declaration\"",
    "\"credential\"",
    "<OPERATOR>",
    "<VARIABLE>",
    "<IDENTIFIER>",
    "<STRING>",
    "<STRING_QUOTED>",
    "<NUMBER>",
    "<LOWERCASE>",
    "<UPPERCASE>",
    "<DIGIT>",
    "\"_\"",
    "\"(\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\".\"",
  };

}
