/* Generated By:JJTree: Do not edit this line. ./PrologParserTreeConstants.java */

package org.peertrust.inference.prolog.parser;

public interface PrologParserTreeConstants
{
  public int JJTPARSEGOAL = 0;
  public int JJTGOAL = 1;
  public int JJTLITERAL = 2;
  public int JJTATOM = 3;
  public int JJTTERMLIST = 4;
  public int JJTTERM = 5;
  public int JJTCOMPOUNDTERM = 6;
  public int JJTLIST = 7;
  public int JJTLETTER = 8;
  public int JJTLETTERS = 9;
  public int JJTCHARACTER = 10;
  public int JJTCHARACTERS = 11;
  public int JJTDIGITS = 12;
  public int JJTNUMBER = 13;
  public int JJTCONSTANT = 14;
  public int JJTVARIABLE = 15;
  public int JJTFUNCTOR = 16;
  public int JJTPREDICATE = 17;


  public String[] jjtNodeName = {
    "parseGoal",
    "Goal",
    "Literal",
    "Atom",
    "TermList",
    "Term",
    "CompoundTerm",
    "List",
    "Letter",
    "Letters",
    "Character",
    "Characters",
    "Digits",
    "Number",
    "Constant",
    "Variable",
    "Functor",
    "Predicate",
  };
}
