/* Generated By:JavaCC: Do not edit this line. PeerTrustParserConstants.java */
package de.l3s.ppt.peertrustparser.javacc;

public interface PeerTrustParserConstants {

  int EOF = 0;
  int DIGIT = 5;
  int SIGNED_BY = 6;
  int LOWER_CASE = 7;
  int UPPER_CASE = 8;
  int UNDERSCORE = 9;
  int ISSUER_CHAR = 10;
  int REQUESTER_CHAR = 11;
  int OPENING_BRACKET = 12;
  int CLOSING_BRACKET = 13;
  int OPENING_SQUARE_BRACKET = 14;
  int CLOSING_SQUARE_BRACKET = 15;
  int RULE_SEPARATOR = 16;
  int COMMA = 17;
  int VERTICAL_SLASH = 18;
  int DOT = 19;
  int ANY_CHARACTER = 20;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIGIT>",
    "\"signedBy\"",
    "<LOWER_CASE>",
    "<UPPER_CASE>",
    "\"_\"",
    "\"@\"",
    "\"$\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<-\"",
    "\",\"",
    "\"|\"",
    "\".\"",
    "<ANY_CHARACTER>",
  };

}
