/* Generated By:JavaCC: Do not edit this line. PeerTrustParserConstants.java */
package de.l3s.ppt.peertrustparser.javacc;

public interface PeerTrustParserConstants {

  int EOF = 0;
  int DIGIT = 5;
  int SIGNED_BY = 6;
  int LOWER_CASE = 7;
  int UPPER_CASE = 8;
  int UNDERSCORE = 9;
  int ISSUER_CHAR = 10;
  int REQUESTER_CHAR = 11;
  int OPENING_BRACKET = 12;
  int CLOSING_BRACKET = 13;
  int OPENING_SQUARE_BRACKET = 14;
  int CLOSING_SQUARE_BRACKET = 15;
  int RULE_SEPARATOR = 16;
  int COMMA = 17;
  int VERTICAL_SLASH = 18;
  int DOT = 19;
  int START_SINGLE_LINE_COMMENT = 20;
  int START_SINGLE_LINE_COMMENT2 = 21;
  int START_MULTIPLE_LINE_COMMENT = 22;
  int ANY_CHARACTER = 23;
  int END_SINGLE_LINE_COMMENT = 24;
  int ANY_CHAR = 25;
  int END_MULTIPLE_LINE_COMMENT = 26;
  int _ANY_CHARACTER = 27;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_MULTIPLE_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIGIT>",
    "\"signedBy\"",
    "<LOWER_CASE>",
    "<UPPER_CASE>",
    "\"_\"",
    "\"@\"",
    "\"$\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<-\"",
    "\",\"",
    "\"|\"",
    "\".\"",
    "\"//\"",
    "\"%\"",
    "\"/*\"",
    "<ANY_CHARACTER>",
    "<END_SINGLE_LINE_COMMENT>",
    "<ANY_CHAR>",
    "\"*/\"",
    "<_ANY_CHARACTER>",
  };

}
