/* Generated By:JavaCC: Do not edit this line. PeerTrustGrammarConstants.java */
public interface PeerTrustGrammarConstants {

  int EOF = 0;
  int DIGITS = 17;
  int SMALLLETTERS = 18;
  int BIGLETTERS = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"<-\"",
    "\"signedBy\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"@\"",
    "\"$\"",
    "\",\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"_\"",
    "<DIGITS>",
    "<SMALLLETTERS>",
    "<BIGLETTERS>",
  };

}
