/* Generated By:JavaCC: Do not edit this line. ProtuneParserConstants.java */
package de.l3s.ppt.protuneparser.javacc;

public interface ProtuneParserConstants {

  int EOF = 0;
  int DIGIT = 5;
  int LOWER_CASE = 6;
  int UPPER_CASE = 7;
  int UNDERSCORE = 8;
  int INCLUDE = 9;
  int DECLARATION = 10;
  int CREDENTIAL = 11;
  int IN = 12;
  int OPENING_BRACKET = 13;
  int CLOSING_BRACKET = 14;
  int OPENING_SQUARE_BRACKET = 15;
  int CLOSING_SQUARE_BRACKET = 16;
  int NEG_SYMBOL = 17;
  int RULE_SEPARATOR = 18;
  int COMMA = 19;
  int SEMICOLON = 20;
  int DOT = 21;
  int OPERATOR = 22;
  int START_SINGLE_QUOTE = 23;
  int START_DOUBLE_QUOTE = 24;
  int START_SINGLE_LINE_COMMENT = 25;
  int START_SINGLE_LINE_COMMENT2 = 26;
  int START_MULTIPLE_LINE_COMMENT = 27;
  int END_SINGLE_LINE_COMMENT = 28;
  int END_SINGLE_QUOTE = 29;
  int END_DOUBLE_QUOTE = 30;
  int ANY_CHAR = 31;
  int END_MULTIPLE_LINE_COMMENT = 32;
  int ANY_CHARACTER = 33;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_SINGLE_QUOTE = 2;
  int IN_DOUBLE_QUOTE = 3;
  int IN_MULTIPLE_LINE_COMMENT = 4;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIGIT>",
    "<LOWER_CASE>",
    "<UPPER_CASE>",
    "\"_\"",
    "\"include\"",
    "\"declaration\"",
    "\"credential\"",
    "\"in\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<NEG_SYMBOL>",
    "<RULE_SEPARATOR>",
    "\",\"",
    "\":\"",
    "\".\"",
    "<OPERATOR>",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"//\"",
    "\"%\"",
    "\"/*\"",
    "<END_SINGLE_LINE_COMMENT>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<ANY_CHAR>",
    "\"*/\"",
    "<ANY_CHARACTER>",
  };

}
