/* Generated By:JavaCC: Do not edit this line. ProtuneParserConstants.java */
package de.l3s.ppt.protuneparser.javacc;

public interface ProtuneParserConstants {

  int EOF = 0;
  int DIGIT = 5;
  int INCLUDE = 6;
  int DECLARATION = 7;
  int LOWER_CASE = 8;
  int UPPER_CASE = 9;
  int UNDERSCORE = 10;
  int OPENING_BRACKET = 11;
  int CLOSING_BRACKET = 12;
  int OPENING_SQUARE_BRACKET = 13;
  int CLOSING_SQUARE_BRACKET = 14;
  int NEG_SYMBOL = 15;
  int RULE_SEPARATOR = 16;
  int COMMA = 17;
  int ID_SEPARATOR = 18;
  int SEMICOLON = 19;
  int DOT = 20;
  int OPERATOR = 21;
  int EQUAL = 22;
  int START_SINGLE_QUOTE = 23;
  int START_DOUBLE_QUOTE = 24;
  int ANY_CHARACTER = 25;
  int END_SINGLE_QUOTE = 26;
  int END_DOUBLE_QUOTE = 27;
  int ANY_CHAR = 28;

  int DEFAULT = 0;
  int IN_SINGLE_QUOTE = 1;
  int IN_DOUBLE_QUOTE = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIGIT>",
    "\"include\"",
    "\"declaration\"",
    "<LOWER_CASE>",
    "<UPPER_CASE>",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<NEG_SYMBOL>",
    "<RULE_SEPARATOR>",
    "\",\"",
    "<ID_SEPARATOR>",
    "\":\"",
    "\".\"",
    "<OPERATOR>",
    "\"=\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<ANY_CHARACTER>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<ANY_CHAR>",
  };

}
